### ISSUE TITLE
Documentation for XDMA

### ISSUE THREAD

**Issue by Prandr** [hmaarrfk/dma_ip_drivers#7]
Is there software documentation for Xilinx DMA?
There is a detailed [Guide for QDMA](https://xilinx.github.io/dma_ip_drivers/2020.2/QDMA/linux-kernel/html/index.html), but I was unable to find anything if the sort for QDMA, only Appendix A in PG195 and barely commented example tools.

To be clear: I wouldn't like to ask you to make documentation. Just whether you know, where it could found, since you have been working with XDMA software for a long time.

**Comment by hmaarrfk** [comment]
I the upstream docs are: https://docs.xilinx.com/viewer/book-attachment/Amxex287WoAaBahiV1hh6w/uNAKBniUzuZZZdTJuqBVqA

**Comment by Prandr** [comment]
Thank you for your response.
I meant detailed documentation for the host programming and interface to the driver.
For example which functions are meant to be used by the user.
or description of request codes for ioctl. 
Do you know where (if anywhere) such information could be found?

**Comment by hmaarrfk** [comment]
i remember just writing to the files (on linux) that are generated in `/dev` when the driver detects the FPGA.

**Comment by Prandr** [comment]
I take it as you don't know the answer to the initial question therefore such documentation very likely does not exist.
Thank you in any case.

**Comment by hmaarrfk** [comment]
You should post on their forum for that.

Sorry i haven't been able to help more. I haven't used XDMA in a while.
